<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <AssemblyName>MoreBotsPrepatch</AssemblyName>
    <Description>MoreBotsAPI Prepatch needed to add custom bots to the client.</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release</Configurations>
    <RootNamespace>MoreBotsAPI.Prepatch</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
		<Reference Include="Assembly-CSharp">
		  <HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
		<Private>false</Private></Reference>
		<Reference Include="spt-common">
		  <HintPath>$(SPTPath)\BepInEx\plugins\spt\spt-common.dll</HintPath>
		<Private>false</Private></Reference>
    <Reference Include="0Harmony">
      <HintPath>$(SPTPath)\BepInEx\core\0Harmony.dll</HintPath>
    <Private>false</Private></Reference>
    <Reference Include="BepInEx">
      <HintPath>$(SPTPath)\BepInEx\core\BepInEx.dll</HintPath>
    <Private>false</Private></Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>$(SPTPath)\BepInEx\core\Mono.Cecil.dll</HintPath>
    <Private>false</Private></Reference>
		<Reference Include="Newtonsoft.Json">
		  <HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll</HintPath>
		<Private>false</Private></Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
    <Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    <Private>false</Private></Reference>
  </ItemGroup>

  <Target Condition="'$(DeployToGame)' == 'true'" Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;$(TargetPath)&quot; &quot;$(SPTPath)\BepInEx\patchers\$(TargetFileName)&quot;" />
  </Target>

</Project>
